#define SETBIT(WORD,BP) WORD|=1<<BP
#define CLRBIT(WORD,BP) WORD&=~(1<<BP)
#define CPLBIT(WORD,BP) WORD^=(1<<BP)
#define WRITEBIT(WORD,BP,BIT) WORD=((WORD&~(1<<BP))|(BIT<<BP))
#define WRITENIBBLE(WORD,SBP,NIBBLE) WORD=((WORD&~(0xf<<SBP))|(NIBBLE<<SBP))
#define WRITEBYTE(WORD,SBP,BYTE) WORD=((WORD&~(0xff<<SBP))|(BYTE<<SBP))
#define WRITEHWORD(WORD,SBP,HWORD) WORD=((WORD&~(0xffff<<SBP))|(HWORD<<SBP))
#define READBIT(WORD,BP) ((WORD>>BP)&1)
//#define CLRBYTE(WORD,BYTE) WORD&=~(0XFF<<BYTE)
#define CLEARBYTE(REG,MASK) REG = MASK
